create_clock -period 20.000 [get_ports SYS_CLK_IN]
set_property IOSTANDARD LVCMOS33 [get_ports SYS_CLK_IN]
set_property PACKAGE_PIN M19 [get_ports SYS_CLK_IN]

set_property PACKAGE_PIN M17 [get_ports UART_1_0_rxd]
set_property PACKAGE_PIN L17 [get_ports UART_1_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_1_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_1_0_txd]


set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_DATA_IN_PIN_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_CLK_COMMON_OUT1_0]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_CLK_COMMON_OUT2_0]
set_property PACKAGE_PIN Y18 [get_ports ADC_CLK_COMMON_OUT1_0]
set_property PACKAGE_PIN T22 [get_ports ADC_CLK_COMMON_OUT2_0]
set_property PACKAGE_PIN V22 [get_ports {ADC_DATA_IN_PIN_0[0]}]
set_property PACKAGE_PIN W22 [get_ports {ADC_DATA_IN_PIN_0[1]}]
set_property PACKAGE_PIN Y20 [get_ports {ADC_DATA_IN_PIN_0[2]}]
set_property PACKAGE_PIN Y21 [get_ports {ADC_DATA_IN_PIN_0[3]}]
set_property PACKAGE_PIN AA22 [get_ports {ADC_DATA_IN_PIN_0[4]}]
set_property PACKAGE_PIN AB22 [get_ports {ADC_DATA_IN_PIN_0[5]}]
set_property PACKAGE_PIN AA21 [get_ports {ADC_DATA_IN_PIN_0[6]}]
set_property PACKAGE_PIN AB21 [get_ports {ADC_DATA_IN_PIN_0[7]}]
set_property PACKAGE_PIN AB20 [get_ports {ADC_DATA_IN_PIN_0[8]}]
set_property PACKAGE_PIN AB19 [get_ports {ADC_DATA_IN_PIN_0[9]}]
set_property PACKAGE_PIN Y19 [get_ports {ADC_DATA_IN_PIN_0[10]}]
set_property PACKAGE_PIN AA19 [get_ports {ADC_DATA_IN_PIN_0[11]}]
set_property PACKAGE_PIN AA16 [get_ports {ADC_DATA_IN_PIN_0[12]}]
set_property PACKAGE_PIN AB16 [get_ports {ADC_DATA_IN_PIN_0[13]}]

set_clock_groups -quiet -asynchronous -group [get_clocks -quiet clk_fpga_0] -group [get_clocks -quiet clk_out4_ad9248clk]
set_clock_groups -quiet -asynchronous -group [get_clocks -quiet clk_out2_ad9248clk] -group [get_clocks -quiet clk_out4_ad9248clk]
set_clock_groups -quiet -asynchronous -group [get_clocks -quiet clk_out3_ad9248clk] -group [get_clocks -quiet clk_out4_ad9248clk]

