# Copyright (C) 2023-2025 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.16)
enable_language(C ASM CXX)

# Board-side application sources.  Host simulation tests intentionally stay
# outside this list because each of them has its own main().
set(USER_COMPILE_SOURCES
    "main.c"
    "acquisition.c"
    "calibration.c"
    "signal_analysis.c"
    "app_print.c"
    "serial_link.c"
    "display_port.c"
    "platform.c"
)

set(USER_COMPILE_DEFINITIONS)
set(USER_UNDEFINED_SYMBOLS "__clang__")
set(USER_INCLUDE_DIRECTORIES)

set(USER_COMPILE_WARNINGS_ALL -Wall)
set(USER_COMPILE_WARNINGS_EXTRA -Wextra)
set(USER_COMPILE_WARNINGS_AS_ERRORS)
set(USER_COMPILE_WARNINGS_CHECK_SYNTAX_ONLY)
set(USER_COMPILE_WARNINGS_PEDANTIC)
set(USER_COMPILE_WARNINGS_PEDANTIC_AS_ERRORS)
set(USER_COMPILE_WARNINGS_INHIBIT_ALL)
set(USER_COMPILE_OPTIMIZATION_LEVEL -O2)
set(USER_COMPILE_OPTIMIZATION_OTHER_FLAGS)
set(USER_COMPILE_DEBUG_LEVEL -g3)
set(USER_COMPILE_DEBUG_OTHER_FLAGS)
set(USER_COMPILE_VERBOSE)
set(USER_COMPILE_ANSI)
set(USER_COMPILE_OTHER_FLAGS)
set(USER_COMPILE_RELAXATION "-Wl,--no-relax")
set(USER_COMPILE_GARBAGE "")

set(USER_LINK_NO_START_FILES)
set(USER_LINK_NO_DEFAULT_LIBS)
set(USER_LINK_NO_STDLIB)
set(USER_LINK_OMIT_ALL_SYMBOL_INFO)
set(USER_LINK_LIBRARIES m)
set(USER_LINK_DIRECTORIES)
set(USER_LINKER_SCRIPT "${CMAKE_SOURCE_DIR}/lscript.ld")
set(USER_LINK_OTHER_FLAGS)

set(USER_COMPILE_OPTIONS
    " ${USER_COMPILE_WARNINGS_ALL}"
    " ${USER_COMPILE_WARNINGS_EXTRA}"
    " ${USER_COMPILE_WARNINGS_AS_ERRORS}"
    " ${USER_COMPILE_WARNINGS_CHECK_SYNTAX_ONLY}"
    " ${USER_COMPILE_WARNINGS_PEDANTIC}"
    " ${USER_COMPILE_WARNINGS_PEDANTIC_AS_ERRORS}"
    " ${USER_COMPILE_WARNINGS_INHIBIT_ALL}"
    " ${USER_COMPILE_OPTIMIZATION_LEVEL}"
    " ${USER_COMPILE_OPTIMIZATION_OTHER_FLAGS}"
    " ${USER_COMPILE_DEBUG_LEVEL}"
    " ${USER_COMPILE_DEBUG_OTHER_FLAGS}"
    " ${USER_COMPILE_VERBOSE}"
    " ${USER_COMPILE_ANSI}"
    " ${USER_COMPILE_OTHER_FLAGS}"
)

foreach(entry ${USER_UNDEFINED_SYMBOLS})
    list(APPEND USER_COMPILE_OPTIONS " -U${entry}")
endforeach()

set(USER_LINK_OPTIONS
    " ${USER_LINK_NO_START_FILES}"
    " ${USER_LINK_NO_DEFAULT_LIBS}"
    " ${USER_LINK_NO_STDLIB}"
    " ${USER_LINK_OMIT_ALL_SYMBOL_INFO}"
    " ${USER_LINK_OTHER_FLAGS}"
)
